"""user, couple 테이블 수정

Revision ID: 12b2380f51db
Revises: cc0b6a5a7f75
Create Date: 2025-08-11 22:03:22.561449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b2380f51db'
down_revision: Union[str, Sequence[str], None] = 'cc0b6a5a7f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
