"""add couple table

Revision ID: 46afadb404f2
Revises: 1229c6716ba1
Create Date: 2025-08-04 15:14:35.475000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46afadb404f2'
down_revision: Union[str, Sequence[str], None] = '1229c6716ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couple',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couple_id'), 'couple', ['id'], unique=False)
    op.add_column('user', sa.Column('couple_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'couple', ['couple_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'couple_id')
    op.drop_index(op.f('ix_couple_id'), table_name='couple')
    op.drop_table('couple')
    # ### end Alembic commands ###
