"""couple table 수정

Revision ID: 49f615db5d7f
Revises: c1758a59a467
Create Date: 2025-08-07 10:50:01.363952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f615db5d7f'
down_revision: Union[str, Sequence[str], None] = 'c1758a59a467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couple', sa.Column('room_pwd', sa.String(length=255), nullable=False))
    op.add_column('couple', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('couple', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_couple_room_pwd'), 'couple', ['room_pwd'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_couple_room_pwd'), table_name='couple')
    op.drop_column('couple', 'updated_at')
    op.drop_column('couple', 'created_at')
    op.drop_column('couple', 'room_pwd')
    # ### end Alembic commands ###
