"""user, 성별 추가

Revision ID: 92e1f6d6c5d1
Revises: 756474e87447
Create Date: 2025-08-16 18:04:32.323004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e1f6d6c5d1'
down_revision: Union[str, Sequence[str], None] = '756474e87447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_gender', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_user_gender'), 'user', ['user_gender'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_gender'), table_name='user')
    op.drop_column('user', 'user_gender')
    # ### end Alembic commands ###
