"""Add email column to users table

Revision ID: b8e4c632a1de
Revises: c46a7e83e839
Create Date: 2025-07-24 11:40:49.943152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8e4c632a1de'
down_revision: Union[str, Sequence[str], None] = 'c46a7e83e839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_partner_id'), table_name='user')
    op.drop_column('user', 'partner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('partner_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_partner_id'), 'user', ['partner_id'], unique=False)
    # ### end Alembic commands ###
