"""user table 수정

Revision ID: c1758a59a467
Revises: 9c434ef3cefb
Create Date: 2025-08-07 10:46:36.573513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c1758a59a467'
down_revision: Union[str, Sequence[str], None] = '9c434ef3cefb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_pwd', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('user', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_user_user_pwd'), 'user', ['user_pwd'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_pwd'), table_name='user')
    op.alter_column('user', 'user_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'user_id',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'user_pwd')
    # ### end Alembic commands ###
