"""user 테이블 수정

Revision ID: c308adb9161b
Revises: 49f615db5d7f
Create Date: 2025-08-11 21:36:06.139471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c308adb9161b'
down_revision: Union[str, Sequence[str], None] = '49f615db5d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_number', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_user_user_pwd'), table_name='user')
    op.create_index(op.f('ix_user_user_number'), 'user', ['user_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_number'), table_name='user')
    op.create_index(op.f('ix_user_user_pwd'), 'user', ['user_pwd'], unique=False)
    op.drop_column('user', 'user_number')
    # ### end Alembic commands ###
