"""Add email column to users table

Revision ID: cd5dce147139
Revises: 9433f6b47c72
Create Date: 2025-07-24 11:35:47.308635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5dce147139'
down_revision: Union[str, Sequence[str], None] = '9433f6b47c72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('partner_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_user_partner_id'), 'user', ['partner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_partner_id'), table_name='user')
    op.drop_column('user', 'partner_id')
    # ### end Alembic commands ###
